---

- name: logstash-configure | Setup configuration files
  template:
    dest: "{{logstash_confdir}}/conf.d/{{item}}"
    group: "{{logstash_group}}"
    owner: "{{logstash_user}}"
    src: etc/logstash/conf.d/{{item}}.j2
    validate: "{{logstash_home}}/bin/logstash --configtest --config %s"
  notify: [logstash restart]
  with_items: [ 10-inputs.conf, 30-filters.conf, 50-outputs.conf ]
  tags: [logstash, logstash-configure]

- name: logstash-configure | Create patterns directory
  file: path={{logstash_confdir}}/patterns
        state=directory
        recurse=yes
        group={{logstash_group}}
        owner={{logstash_user}}
  tags: [logstash, logstash-configure]

- name: logstash-configure | Setup patterns
  template: src=pattern.j2 dest={{logstash_confdir}}/patterns/{{item[0]}} owner={{logstash_user}} group={{logstash_group}}
  with_items: "{{logstash_config_patterns.items()}}"
  tags: [logstash, logstash-configure]

- name: logstash-configure | Ensure the service is started
  service: name=logstash state=started enabled=yes
  changed_when: False
  tags: [logstash, logstash-configure]
