---

- name: logstash-remove | Ensure the forwarder is stoped
  service: name=logstash-forwarder state=stopped enabled=no
  changed_when: False

- name: logstash-remove | Ensure the server is stoped
  service: name=logstash state=stopped enabled=no
  changed_when: False

- name: logstash-remove | Remove the forwarder
  file: state=absent path=/etc/init/logstash-forwarder.conf